### ISSUE TITLE
Create nav menu component

### ISSUE THREAD

**Issue by floorrinse** [CadmiumRed40/FindAFlick#17]
Create the nav menu that shows firstName, icon, nav menu. 

Visuals:
![Closed-menu](https://user-images.githubusercontent.com/13733055/188254424-4a98bdc7-c89c-4e4c-adcb-9be433786a9a.png)

![Toggled-menu](https://user-images.githubusercontent.com/13733055/188254418-b8fbcccc-872c-495d-a177-3ba23651f6b8.png)

[Whole mockup for reference](https://user-images.githubusercontent.com/80559746/188102456-5721684f-d52e-4ae1-8876-c9becdbeeacc.png)

Things to implement:
- toggle menu
- profile icon
- name is personalized
- should only be shown when logged in

**Comment by AllieGie** [comment]
Everything checked out.
