### ISSUE TITLE
Style the /login page

### ISSUE THREAD

**Issue by floorrinse** [CadmiumRed40/FindAFlick#18]
The router, controller, and view are already done for the `/login` page so this ticket is to style the page.

<img src="https://user-images.githubusercontent.com/13733055/188255027-6fbbf610-9718-4025-9b44-8df3161e8d83.png" width="300">

[Whole mockup for reference](https://user-images.githubusercontent.com/80559746/188102456-5721684f-d52e-4ae1-8876-c9becdbeeacc.png)

Things to implement:
- buttons
- include `sign up`

**Comment by svmarinez** [comment]
98% done; the colors need to be updated to match the mock-up and the errors need to be placed back in as they were taken out during dev
