### ISSUE TITLE
Adding new route to a "User profile"

### ISSUE THREAD

**Issue by CadmiumRed40** [CadmiumRed40/FindAFlick#6]
Adding a user profile to store saved (bookmarked movies).

**Comment by floorrinse** [comment]
Now that I'm thinking more about this ticket, this might already be done in this [ticket](https://github.com/CadmiumRed40/FindAFlick/issues/5). Depending on how that work is done, I'll go from there 👍

**Comment by TonyHerbert22ATX** [comment]
Yea. I went ahead and changed all the routes. I will close this ticket
