### ISSUE TITLE
Connecting API

### ISSUE THREAD

**Issue by CadmiumRed40** [CadmiumRed40/FindAFlick#7]
Finding and Connecting API read client input and update views.

Movie title:
Overall Score:
Genre
User Score:
Release Date:
Director:
Actors:

**Comment by pan-alex** [comment]
Propose to close as this is being addressed with [Issue #11](https://github.com/CadmiumRed40/FindAFlick/issues/11). The plan is to use the Mongo mflix database instead of an API.
